name: chat_app_basic
description: チャットアプリを簡易的に作成

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  go_router: ^3.0.6
  intl: ^0.17.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/kurogoma.png
    - assets/images/friends.png
    - assets/images/github.png
    - assets/images/setting_image.png
    - assets/images/solo_man.png
    - assets/images/camera.png
    - assets/images/file.png
    - assets/images/pikon.png
    - assets/images/lock.png
    - assets/images/send.png
    - assets/images/ufo2.png
    - assets/images/google-icon.png
    - assets/images/line-icon-pop.png
    - assets/images/line-round-default.png
    - assets/images/line-square-default.png
    - assets/images/twitter.png
    - assets/images/twitter-illust.png
    - assets/icons/appstore.png
    - assets/icons/playstore.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appstore.png"
  git:
    url: https://github.com/Davenchy/flutter_launcher_icons.git
    ref: fixMinSdkParseFlutter2.8